version: '3'

services:
  project-service-app:
    container_name: devguild-project-service
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db
    ports:
      - 6000:6000
    volumes:
      - .:/home/app:cached
      - ./package.json:/home/app/package.json:cached
    networks: 
      - devguild-project-service-network

  db-project-service:
    image: postgres:9.4
    container_name: devguild-project-service-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=devguild
      - POSTGRES_PASSWORD=project-service
      - POSTGRES_DB=devguild-project-db
    networks:
      - devguild-project-service-network

networks:
  devguild-project-service-network:
    external:
      name: default_services_network